### ISSUE TITLE
Have Casper set the X-Smartstack-Source header

### ISSUE THREAD

**Issue by bplotnick** [Yelp/casper#45]
Right now Casper relies on the caller's Smartstack to add the `X-Smartstack-Source` header. This is a bit surprising given that the request _to_ Casper will have a source of `casper.main` or whatever.

I think it makes more sense to actually have Casper set this header itself when it proxies the request.

The specific reason that I'd like this is due to the way that I plan on implementing this logic in Envoy. I plan on having a special [priority](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/load_balancing#priority-levels) routing configuration with Casper being the most preferred priority but then failing over gradually to real service.

Example:
```
If X-Smartstack-Source is present:
P0        az-local endpoints (habitat)
P1        region-local endpoints (region)
P2        the rest (ecosystem)

If X-Smartstack-Source is not present
P0        casper endpoints
P1        az-local endpoints (habitat)
P2        region-local endpoints (region)
P3        the rest (ecosystem)
```

There might be other ways that we can implement this, but this seems to be the most straightforward for now. It also gives us the advantage of failing over from Spectre gradually based on health status rather than all at once

@drolando

**Comment by drolando** [comment]
Fixed by https://github.com/Yelp/casper/pull/49

**Comment by bplotnick** [comment]
Reopening since we reverted in #54 54

**Comment by yannlandry** [comment]
Closing again as we're now setting `X-Smartstack-Source` directly in Envoy.
